MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  RPN:
    PRE_NMS_TOP_N_TEST: 9000
    POST_NMS_TOP_N_TEST: 1300
    ANCHOR_SIZES: (8, 16, 32, 64, 128)
    ASPECT_RATIOS: (0.5, 0.85, 1.0, 2.0)
  ROI_HEADS:
    DETECTIONS_PER_IMG: 1300
    SCORE_THRESH: 0.05
  ROI_BOX_HEAD:
    NUM_CLASSES: 2
  BACKBONE:
    CONV_BODY: "R-101-C4"
    FREEZE_CONV_BODY_AT: -1
DATASETS:
  TRAIN: ("kuzushiji_denoised_train_same_label", "kuzushiji_denoised_val_same_label")
  # TEST: ("kuzushiji_denoised_test_use_val_same_label",)
  TEST: ("kuzushiji_denoised_test",)
SOLVER:
  BASE_LR: 0.01
  WARMUP_ITERS: 1500
  WEIGHT_DECAY: 0.0001
  STEPS: (50000, 100000)
  MAX_ITER: 100000
  IMS_PER_BATCH: 2
INPUT:
  MIN_SIZE_TRAIN: (1000, 1200, 1400, 1600)
  MAX_SIZE_TRAIN: 6000
  MIN_SIZE_TEST: 2500
  MAX_SIZE_TEST: 6000
  RANDOM_GRAYSCALE_PROB_TRAIN: 0.3
  FLIP_PROB_TRAIN: 0.0
  VERTICAL_FLIP_PROB_TRAIN: 0.0
  PIXEL_MEAN: [0, 0, 0]
  PIXEL_STD: [1.0, 1.0, 1.0]
  BRIGHTNESS: 0.2
  CONTRAST: 0.2
  SATURATION: 0.2
  HUE: 0.2
TEST:
  IMS_PER_BATCH: 2
  BBOX_AUG:
    ENABLED: True
    GRAYSCALE: True
    H_FLIP: False
    SCALES: (1000, 1100, 1200, 1300, 1400, 1500, 1600, 1700, 1800, 1900, 2000, 2100, 2200, 2300, 2400, 2500)
    MAX_SIZE: 6000
    SCALE_H_FLIP: False
  DETECTIONS_PER_IMG: 1300
